### ISSUE TITLE
Stm32f103 can bus not working

### ISSUE THREAD

**Issue by jwdsoft** [nopnop2002/Arduino-STM32-CAN#17]
Hello
Can you help me figure out why this project is not working for me
It compiles successfully and get uploaded successfully by stlink swd connector
But doesn't send any messages 
The board doesn't work using usb doesn't get recognized so i can't see uart or debug info

**Comment by nopnop2002** [comment]
You can get debug information using a USB-TTL converter.

TX of UART is PA9.
Serial.print() is output to PA9.

I updated README.
Look at the diagram in Communication with ESP8266.

**Comment by zerog2k** [comment]
I do not think you can use CAN and USB on STM32F103 at same time. I think you will have to disable USB, and also I recall someone mentioning that the maple (old stm32 arduino framework enabled USB by default). I'm having issues with newer st-stm32 (stm32 duino, official newer arduino framework, and I suspect it's due to USB, but still troubleshooting this.)

**Comment by nopnop2002** [comment]
As far as I can see in the Reference manual, I think that USB and CAN are not related.

https://www.st.com/resource/en/reference_manual/cd00171190-stm32f101xx-stm32f102xx-stm32f103xx-stm32f105xx-and-stm32f107xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf


I used Arduino_Core_STM32 Ver1.9.0 and confirmed that it works properly.


As far as I know, CAN is not available in maple-core.(Roger Clark core)

**Comment by adamslodki** [comment]
My car have 3 CAN-BUS: first  33.3k, second 125K and  last 500k. It's possible to add 33.3k baudtate to your library? 
I analyzed the code. Another enum should be added:

enum BITRATE {CAN_33.3KBPS, CAN_50KBPS, CAN_100KBPS, CAN_125KBPS, CAN_250KBPS, CAN_500KBPS, CAN_1000KBPS};

and

CAN_bit_timing_config_t can_configs [7] = {{x, y, z}, {2, 13, 45}, {2, 15, 20}, {2, 13, 18}, {2, 13, 9}, {2, 15, 4}, {2, 15, 2}};

But what values to put in place of TS2 = x, TS1 = y, BRP = z?
![image](https://user-images.githubusercontent.com/2067454/99196941-a0696380-278f-11eb-943c-8c5973304a3d.png)

**Comment by maxkr2** [comment]
Hi,
I have the same issue on a STM32F103C8/ BluePill: USB is not working if CAN is active and not detected by Windows. CAN-transceiver is connected to PB8+9 as you told me in the past (issue #19) and I guess Serial.print() was possible via USB. 
Not sure whats wrong now. Hopefully you can give me a hint again.

Update: I guess I used a serial to USB-converter in the past connected to PA9+10 and not Output via on board USB..

**Comment by nopnop2002** [comment]
When using On-Board USB of BluePill, select CDC from Tools → USB support when writing a sketch.

![VitiualComPort-2](https://user-images.githubusercontent.com/6020549/150454332-5f337d7a-695d-497f-adec-b10bfb783ad9.jpg)



After writing the sketch, a new Virtual COM Port will appear.
![VitiualComPort-3](https://user-images.githubusercontent.com/6020549/150454340-a76314ed-8dc4-464c-a006-52fbd9190af7.jpg)




This COM port is connected to the STM32 UART.
You will be able to use the Arduino-IDE serial monitor.
UART ports such as PA9 cannot be used.

However, this method has its drawbacks.
Every time you reset (which happens every time you upload a sketch), the USB port will also be reset.
The USB serial port on the board is disconnected from the Arduino IDE serial monitor and you must close and reopen the serial monitor to reopen the port.
Therefore, you cannot see the message immediately after startup.
Vertual COM Port is a port for USB communication, not for debugging.


__If the USB speed is set to other than Low / Full Speed, the build will not pass.__

```
void setup() {
  Serial.begin(115200);
  while (!Serial) ;
  Serial.println("STM32 Hello start");
}

void loop() {
  Serial.print("Hello from STM32! ");
  Serial.println(millis());
  delay(1000);
}
```
![VitiualComPort-4](https://user-images.githubusercontent.com/6020549/150458336-393615f7-01d6-45d1-89d6-922c9d142153.jpg)




More detail is here.
https://www.onetransistor.eu/2020/01/stm32-bluepill-arduino-support.html

**Comment by maxkr2** [comment]
Hi nopnop2002,
thank you for your detailed explaination. I was sure that I used integrated USB for serial output before, but using an serial-USB-converter at PA9+10 solved my problem: 
I got an output before also by integrated USB without CAN, I am also using CDC but on PlatfomIO and platform=Arduino. 
But with enabled CAN-transceiver the integrated USB was not detected in Windows any more (unknown device).

**Comment by nopnop2002** [comment]
>with enabled CAN-transceiver the integrated USB was not detected

You are right.   
Select [Tools]-> [USB Support:CDC] to enable the virtual COM port.   
But CAN-transceiver and USB Support cannot be used at the same time.
I don’t know why.
Don't use USB Support.   
You have to use USB-Serial Converter.
