### ISSUE TITLE
How to add this files to arduino ide?

### ISSUE THREAD

**Issue by Marcelocm1995** [nopnop2002/Arduino-STM32-CAN#23]
Hi! How to add this files to arduino ide?

**Comment by nopnop2002** [comment]
Software requirements:

STM32 core support for Arduino.
https://github.com/stm32duino/Arduino_Core_STM32

**Comment by Marcelocm1995** [comment]
I already have this "stm32duino" installed, where I put these folders of your library?

Sorry for my english. :)

**Comment by nopnop2002** [comment]
This is sample code, not a library.

Compile immediately.

File -> Open -> stm32f103.ino

**Comment by Marcelocm1995** [comment]
I understand. Now I have tried to compiled but output shows me "'CAN1' was not declared in this scope"

**Comment by nopnop2002** [comment]
What board are you using?


This is my  tool memu.

![stm32f103](https://user-images.githubusercontent.com/6020549/87728261-a52c0400-c7fd-11ea-81b0-7c1833125977.JPG)

**Comment by Marcelocm1995** [comment]
I was using another core, now I installed your core and compiles. Thanks!!!

**Comment by nopnop2002** [comment]
It is good news for me.
