### ISSUE TITLE
Sample program

### ISSUE THREAD

**Issue by saadat925** [nopnop2002/Arduino-STM32-CAN#39]

**Comment by saadat925** [comment]
Dear friend
I want to send 0x01 to identifier 0 only once and then receive 8 bytes data from id = 2bd permanently.  please guide me .  I also used a blue pill.  Thank you

**Comment by nopnop2002** [comment]
This is very simple example for blue  pill.

https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f103

**Comment by saadat925** [comment]
I run this program and get
![۲۰۲۱۰۴۱۸_۱۰۵۵۰۱](https://user-images.githubusercontent.com/79224012/115136388-b2984800-a034-11eb-9ce3-cd2802290838.jpg)
this result.  But I need to send a byte

**Comment by nopnop2002** [comment]
You need to change this code.

https://github.com/nopnop2002/Arduino-STM32-CAN/blob/master/stm32f103/stm32f103.ino#L360

**Comment by saadat925** [comment]
Thanks

**Comment by saadat925** [comment]
Dear sir
Now the canbus is sent on my device in extended mode. If I want to be sent only in standard mode, what do you suggest?

**Comment by nopnop2002** [comment]
change this.

https://github.com/nopnop2002/Arduino-STM32-CAN/blob/master/stm32f103/stm32f103.ino#L376

**Comment by saadat925** [comment]
That is, to replace the extended_format with the standard_ format ?

**Comment by nopnop2002** [comment]
Yes.

**Comment by saadat925** [comment]
Where can I find UNO program?

**Comment by nopnop2002** [comment]
There is a lot of program for UNO in the internet.
