### ISSUE TITLE
Problem when compiling stm32f103.ino

### ISSUE THREAD

**Issue by mamech** [nopnop2002/Arduino-STM32-CAN#41]
Hello

I appreciate the effort done in this project. I have a problem with compilation of  stm32f103.ino 
I got this error:
"C:\Users\XXXXX\Documents\Arduino\libraries\stm32f103\stm32f103.ino: In function 'void CANReceive(CAN_msg_t*)':
stm32f103:242:8: error: 'id' was not declared in this scope
  242 |   if ((id & STM32_CAN_RIR_IDE) == 0) { // Standard frame format
      |        ^~
stm32f103:251:8: error: 'id' was not declared in this scope
  251 |   if ((id & STM32_CAN_RIR_RTR) == 0) { // Data frame
      |        ^~
exit status 1
'id' was not declared in this scope"
I have Arduino IDE 1.8.12
and latest version of STM32duino

**Comment by mamech** [comment]
[](url)

**Comment by mamech** [comment]
![image](https://user-images.githubusercontent.com/18274684/127318007-58e8a45f-46e5-45d2-978b-67b38d847966.png)
This is the configuration I selected.

**Comment by nopnop2002** [comment]
Your code doesn't have this line.

It's different from the github code.

https://github.com/nopnop2002/Arduino-STM32-CAN/blob/master/stm32f103/stm32f103.ino#L243

**Comment by mamech** [comment]
Thank you very much. now compiled successfully.
But I faced a new problem. The program gets stuck in Setup() function and does not continue to loop() function for unknown reason.
`
void setup() {
  Serial.begin(115200);
  Serial.println("Hi 1");
  bool ret = CANInit(CAN_100KBPS, 3);  
   Serial.println("Hi 2");
  if (!ret) while(true);
  Serial.println("Hi 3");
}
`


Only "Hi 1" is printed. so this means to me that this line  :
bool ret = CANInit(CAN_100KBPS, 3); 
is blocking the code for some reason, so code stucks inside CANInit() and does not come out of it. I tried to change the second argument of CANInit() to 0,1,2 and all are the same, the program stucks.
I am using Bluepill.

**Comment by nopnop2002** [comment]
Possible reasons

bluepill does not have a CAN transceiver.

**Comment by mamech** [comment]
I think you mean the blue pill was not connected to CAN transceiver during this test?
The answer is yes, but blue pill itself has CAN controller support, so why do I need a transceiver? And how a hardware transceiver causes the code to get stuck?

**Comment by nopnop2002** [comment]
blue pill itself has CAN controller support.
you need CAN transceiver.

https://github.com/nopnop2002/Arduino-STM32-CAN#wirering

**Comment by mamech** [comment]
Thanks for clarification. I tried to make like echo test using one blue pill and transceiver, but did not work either and still stuck at the same line. I am wondering is it a must to have 2 blue pills with 2 transceivers? can not I use only onle blue pill with CANHigh connected to CANLow so I receive the same message I sent?

**Comment by nopnop2002** [comment]
it a must to have 2 blue pills with 2 transceivers.

CAN is not TR / RX.

Dominant / Recessive is expressed by the voltage difference between CAN HIGH and CAN LOW.

https://www.ti.com/lit/an/slla337/slla337.pdf

https://www.ti.com/lit/an/sloa101b/sloa101b.pdf?ts=1627823619752&ref_url=https%253A%252F%252Fwww.google.com%252F

It may break when CAN Low and CAN High are connected.

**Comment by mamech** [comment]
Thanks, now it is clear. It is first time I use CAN so I am influenced much with UART.
One more question please, CAN network should have master and slave, so these 2 bluepills should be configuered to be one master and the other is slave, so this leads to 2 questions:
1- The code we are talking about is made to make its bluepill a master or slave?
2- If it is a master how to reverse its function to be a slave (or vice versa) ?
Thanks

**Comment by nopnop2002** [comment]
There is no master / slave in the CAN network.

There is just a sender / receiver.

Anyone can be a sender.
Anyone can be a receiver.


However, __only one node__ can be the sender at a particular time.
Multiple nodes cannot be senders at the same time.
The sender may be called bus master.
The sender dominate CAN-BUS.

If a plurality of nodes try to transmit at the same time, only one sender is determined according to the priority.
Low priority nodes give up sending.


The priority is written here.

https://www.ti.com/lit/an/sloa101b/sloa101b.pdf?ts=1627823619752&ref_url=https%253A%252F%252Fwww.google.com%252F
