### ISSUE TITLE
Support stm32f105 with 2 can

### ISSUE THREAD

**Issue by avarcod** [nopnop2002/Arduino-STM32-CAN#42]
Is it possible to add support for stm32f105 with two cans?

**Comment by nopnop2002** [comment]
No

because,
STM32 core support for Arduino does not support STM32F105.

https://github.com/stm32duino/Arduino_Core_STM32

You can send a [New Variant] request here.

https://github.com/stm32duino/Arduino_Core_STM32/issues/722
