### ISSUE TITLE
Adapt to stm32f767 custom board

### ISSUE THREAD

**Issue by 0v3rcl0ck3d** [nopnop2002/Arduino-STM32-CAN#43]
Hello nopnop2002,
Thanks for your create work.
I want do adapt your code to a board using the stm32f767 but I don't know how to get this done. Could you provide me some information which code is specific for the processor? Where did you get the information to support the other processors?

**Comment by nopnop2002** [comment]
You need to read the Reference manual carefully.

Especially RCC GPIO and bxCAN are important.


https://www.st.com/resource/en/reference_manual/dm00224583-stm32f76xxx-and-stm32f77xxx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf

---

STM32F765xx, STM32F767xx, STM32F768Ax and STM32F769xx alternate function mapping is here.
bxCAN seems to use AF9.

https://www.st.com/resource/en/datasheet/stm32f765zi.pdf

---

You can use this for CAN Bit Time Calculation.

http://www.bittiming.can-wiki.info/

**Comment by 0v3rcl0ck3d** [comment]
Actually, I did read the Reference manual carefully. However, this is my first time using low level code and the first time I need CAN.
From what I saw in the manual, it seems that the CAN part of the 767 and the 466 are nearly the same. So I just used the code for the 466 and tried to get it working. 
However, I was not able to send a message.

I also tried to use the HAL CAN functions from the Core but the documentation is not very detailed.

Thanks for your help, but it seems I am not able to implement it with this informations.

I was not able to find a example of CAN implementation for the Arduino IDE for this processor at all. Since this is part of a bigger project that is already in production, I can not just switch to Cube IDE.

If you have any further informations that could help me, I would really appreciate it.

**Comment by nopnop2002** [comment]
>From what I saw in the manual, it seems that the CAN part of the 767 and the 466 are nearly the same. 

It looks the same at first glance, but it may be slightly different.

I will buy STM32F767 if it becomes more cheap, but it is expensive for me.

**Comment by 0v3rcl0ck3d** [comment]
If you just need a 767 and could help me with it, this should be doable. However, we are short on time and need a working solution within days. If there is a way to achieve this, let me know.

**Comment by nopnop2002** [comment]
>we are short on time and need a working solution within days. 


It's a lot of work.
It is impossible in a short time.

**Comment by nopnop2002** [comment]
Added F7 series
