### ISSUE TITLE
Send Fail

### ISSUE THREAD

**Issue by ciamia** [nopnop2002/Arduino-STM32-CAN#46]
Hi, ı want to receive messages from arduino mega with canbus on stm32f407. When upload code it says CAN initilization is succesfull but doesnt receive anything. Arduino prints sending is succesfull. But I cant figure out why it doesnt work. And I counldnt find your Sender Codes anywhere, are they avaliable?

**Comment by nopnop2002** [comment]
It is work fine with stm32F405/406.

https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f407

**Comment by ciamia** [comment]
I used your code but I am getting send fail on my screen. I tried the things you said and they didnt seem to work for me. My two arduinos talk to each other just fine but when I add stm32 with your code my receiver doesnt get anything and yours say send fail.

**Comment by nopnop2002** [comment]
If the transmission fails, these are the possible causes.

There is no receiving app on CanBus.
The speed does not match the receiver.
There is no terminating resistor on the CanBus.
There are three terminating resistors on the CanBus.
The resistance value of the terminating resistor is incorrect.
Stub length in CAN bus is too long.
Though the ISO11898 Standard specifies a maximum bus length of 40m and maximum stub length of 0.3m at 1Mbps. See [here](https://e2e.ti.com/support/interface-group/interface/f/interface-forum/378932/iso1050-can-bus-stub-length).

**Comment by nopnop2002** [comment]
Your CAN-BUS may be affected by noise.


If you review the wiring of CAN-BUS, it may work.

It occurs when the wire cable is thin or wire cable is crossing.   
It is preferable to use twisted wire.   

I changed the wire cable to twisted wire. Fixed.
![CAN-SendFail](https://user-images.githubusercontent.com/6020549/185773802-5ef8ff6d-fcec-4a89-a4a2-3d14ce7bba40.jpg)

**Comment by ciamia** [comment]
I am going to try the cables. Do you have the code for arduino receiver. Did you share it somewhere? Maybe I can try that.

**Comment by ciamia** [comment]
And I tried the code you said it works perfectly. My UART-USB converter connection is fine.

**Comment by ciamia** [comment]
My problem isnt solved. Only Serial connection is ok. But communication problem continious.

**Comment by ciamia** [comment]
> 

?

**Comment by ciamia** [comment]
I really need to try the arduino code you used.

**Comment by nopnop2002** [comment]
>I really need to try the arduino code you used.

Read carefully.

https://github.com/nopnop2002/Arduino-STM32-CAN/blob/master/README.md

README say;
Communication with Arduino-UNO
You can use [this](https://github.com/coryjfowler/MCP_CAN_lib) library.
---

If you search the Internet, you will find a lot of sample code.

**Comment by ciamia** [comment]
Sir, I am trying to send data from Mega and Stm32 then read it from Nano. Mega and Nano works perfectly together but when I connect Stm32 with your code. Nano stops receiving and Stm32 says send fail. I connected resistors and everyting. I am asking if you shared the code that you used in Arduino to try it. I have read the README.

**Comment by nopnop2002** [comment]
>I am asking if you shared the code that you used in Arduino to try it. 

https://github.com/coryjfowler/MCP_CAN_lib

>Mega and Nano works perfectly together but when I connect Stm32 with your code. Nano stops receiving and Stm32 says send fail. 


simply a wire cable or terminating resistor or bitrate or connection problem.


Is the STM32 BitRate correct?

Are STM32 wires short enough?

Are the STM32 wires well shielded?

Are all wires adequately shielded?

Are the terminating resistors really on both ends?


I changed the wire cable to twisted wire. It Fixed.
![CAN-SendFail](https://user-images.githubusercontent.com/6020549/185773802-5ef8ff6d-fcec-4a89-a4a2-3d14ce7bba40.jpg)

**Comment by nopnop2002** [comment]
1000KBPS is susceptible to noise.

Try it at 250KBPS or 500KBPS.

**Comment by nopnop2002** [comment]
>Mega and Nano works perfectly together but when I connect Stm32 with your code. Nano stops receiving and Stm32 says send fail.

Mega and Nano are working perfectly, what happens when you add STM32 to CAN-BUS?

Connect stm32 to tranceiver.
Add tranceiver to CAN-BUS.
But without turning on the STM32.

**Comment by ciamia** [comment]
I solved the problems they work now thank you for your help. I used the arduino codes you suggested and changed the clock settings. It works perfectly now.

**Comment by nopnop2002** [comment]
I found that:

STM32F405/407 can use a Virtual COM port.
If you enable Virtual COM port, you can use the USB port as a serial port.

With STM32F103, Basic Extended CAN(BxCan) and USB Support **can not** be used at the same time.

With STM32F405/407, Basic Extended CAN(BxCan) and USB Support **can** be used at the same time.

**Comment by ciamia** [comment]
Yes, I used USB as a serial port
