### ISSUE TITLE
Canard

### ISSUE THREAD

**Issue by ciamia** [nopnop2002/Arduino-STM32-CAN#47]
Hi sir i wanted to ask you someting I want to use UAVCAN to connect my stm32f4 to autopilot. I was trying to use your codes in canard example but I couldnt understand how. i downloaded the file and opened example.ino but that code does nothing. Can you explain to me how to do it?

**Comment by nopnop2002** [comment]
This can be compiled using the ArduinoIDE.

Requires Arduino IDE.


Original is here.
https://github.com/geosmall/UAVCAN-for-STM32-Arduino


Library is here.
https://github.com/OpenCyphal/libcanard
