### ISSUE TITLE
Discuss: other ways to clear mailbox?

### ISSUE THREAD

**Issue by i-make-robots** [nopnop2002/Arduino-STM32-CAN#57]
First, love this code, thank you for being so clever and generous with your work.

I'm building a CAN bus stepper controller.  Timing is critical for good stepping.  Steps have to happen as fast as possible.

From https://github.com/nopnop2002/Arduino-STM32-CAN/blob/master/stm32f407/stm32f407.ino
```
    // Wait until the mailbox is empty
    while(CAN1->sTxMailBox[0].TIR & 0x1UL && count++ < 1000000);
```
This is blocking.  The stepper still moves... way below expected performance levels.  I can shorten the 1M and then I get send failures.
I'm looking for ways to send and receive without blocking.  If you have a demo of this I would be very interested!
If I figure out a way myself I'll post back here.

Thank you!

**Comment by nopnop2002** [comment]
>I'm looking for ways to send and receive without blocking. 

```
    // Send Go
    CAN1->sTxMailBox[0].TIR = out | STM32_CAN_TIR_TXRQ;
```


That's all there is to sending.
It should be over in an instant.

```
    // Wait until the mailbox is empty
    while(CAN1->sTxMailBox[0].TIR & 0x1UL && count++ < 1000000);

    // The mailbox don't becomes empty while loop
    if (CAN1->sTxMailBox[0].TIR & 0x1UL) {
      Serial.println("Send Fail");
      Serial.println(CAN1->ESR);
      Serial.println(CAN1->MSR);
      Serial.println(CAN1->TSR);
    }
```

This is checking if the send was successful.

There are two ways to know if the send was successful without waiting.

- Uses a transmission completion interrupt.
You need to set the CAN interrupt enable register (CAN_IER) appropriately.

- Check mailbox space before sending the next message.
STM32 has Three transmit mailboxes.
Three transmit mailboxes are provided to the software for setting up messages. 
A maximum of 3 send requests can be made.
The transmission Scheduler decides which mailbox has to be transmitted first.
You can specify which mailbox has priority using the CAN Master Control Register (CAN_MCR).
You can tell if a mailbox is free using the CAN Transmit Status Register (CAN_TSR).
When all 3 tx mailboxes are pending, the next message cannot be sent unless the sending is canceled or the sending is completed.
When all 3 tx mailboxes are pending, you can choose to cancel the transmission or wait for the transmission to complete.
It depends on your application requirements.

---


# from reference manual

![can-transmit](https://user-images.githubusercontent.com/6020549/236161066-d8002a2d-92b7-45c4-aca9-5395a851ca33.jpg)




![mailbox](https://user-images.githubusercontent.com/6020549/236179012-6784114c-4efc-4a41-b928-fab0a6aa4d31.jpg)


---


If all three tx mailboxes are pending, whether to cancel the send or wait for the send to complete depends on the requirements of the application.
Read the reference manual carefully and modify the source code as necessary.
Therefore there is no sample code.

If all 3 tx mailboxes are pending for a long time, there may be an error.
CAN Error Status Register (CAN_ESR) should be checked.

We wish you good luck.
