### ISSUE TITLE
Mistake in Line 277

### ISSUE THREAD

**Issue by KGBRUS1** [nopnop2002/Arduino-STM32-CAN#58]
Dear Nopnp2002,

i think there is a mistake in Line 277 " GPIOA->ODR |= 0x1UL << 12;       // PA12 Upll-up"

The PA12 is the TX pin, i think that the RX pin (PA11) must be usesed in this line

simulat to  GPIOB->ODR |= 0x1UL << 8;        // PB8 Upll-up (this is RX Pin

best regards

Kay

by the way, thanks for your Sketch!

**Comment by nopnop2002** [comment]
>i think there is a mistake in Line 277 " GPIOA->ODR |= 0x1UL << 12; // PA12 Upll-up"


which subdirectory?

**Comment by KGBRUS1** [comment]
Sorry:

[Arduino-STM32-CAN](https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master)/[stm32f103](https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f103)
/stm32f103.ino

**Comment by nopnop2002** [comment]
It looks like a bug.
Test then fix.
Thanks for the report.

**Comment by KGBRUS1** [comment]
Thanks for your excelent work! i never get CAN and Blue Pill running without your sketch!

**Comment by nopnop2002** [comment]
Fixed.

thank you.
