### ISSUE TITLE
Support for working with stm32f411 and changing contacts PA11 and PA12

### ISSUE THREAD

**Issue by brightproject** [nopnop2002/Arduino-STM32-CAN#65]
Hello @nopnop2002 .
I see that your wonderful library supports `stm32f103` and `stm32f413` microcontrollers.
I have `stm32f411ceu6` microcontroller and `mcp2551` CAN xcvr

![stm32f411_mcp2551](https://github.com/user-attachments/assets/78c067f1-214e-40ce-84af-8338f47f01d5)

Can I run the code on it?
And can I change the contacts, from `PA11 PA12` to `PB8 PB9`?
I have never worked with `CAN` bus before, so the questions are very stupid.
Maybe it makes sense to open discussions in your repository, so as not to post such questions in the issue?
In the code assembly I use:

> https://github.com/stm32duino/Arduino_Core_STM32

and `vscode+platformio`.

I hope I can adapt the code to my microcontroller `stm32f411ceu6`.

**Comment by nopnop2002** [comment]
STM32F411 does not have CAN functionality.

https://www.st.com/ja/microcontrollers-microprocessors/stm32f411/products.html

Not all STM32s have CAN functionality.

When using the CAN function with STM32, the MCU must be selected carefully.

**Comment by brightproject** [comment]
> When using the CAN function with STM32, the MCU must be selected carefully.

Thanks for the clarification, quite annoying.
But I will use the module temporarily:

![Arduino-MCP2515-CAN-Bus-Interface-MCP2515-CAN-Module-Components](https://github.com/user-attachments/assets/365de5d0-316b-4fdb-95be-c90e3fd538c6)

**Comment by nopnop2002** [comment]
The CAN transceiver (TJA1050) used in this module is a 5V power supply, so
For 3.3V machines such as STM32, SPI level shifting is required.

**Comment by nopnop2002** [comment]
Not all GPIOs of STM32 are 5V tolerant.


Please note that this module is 5V powered, so you will need to use a 5V tolerant GPIO.


I replaced the transceiver chip of the CAN module from the 5V specification TJA1050 to the 3.3V specification SN65HVD230.

Since the MCP2515 can be used with 2.7 to 5.5V, it can now be used with a 3.3V power supply even in environments where 5V cannot be provided.



![MCP2515_CAN_3V3](https://github.com/user-attachments/assets/d19b3e39-5664-4c88-bc8f-19512091d4fd)

**Comment by brightproject** [comment]
> I replaced the transceiver chip

You are great that you suggested this🙂
And did you change the quartz from `8 kHz` to something with a `higher` frequency?
I have chips `SN65HVD230`, I also thought about soldering them onto the module `MCP2515`.

**Comment by nopnop2002** [comment]
>did you change the quartz from 8 kHz to something with a higher frequency?

No.

**Comment by brightproject** [comment]
> No.

Please tell me to use the board with the controller and transceiver `MCP2515` + `SN65HVD230`

![318240999-cd69745e-c7c9-4419-aeb0-4611c17f800a](https://github.com/user-attachments/assets/63f9a0f2-1be1-40bc-866e-e5e65064b519)


And `stm32411ceu6` via the `SPI` bus

What code should I use from your repo?

All examples, including this one

> https://github.com/nopnop2002/Arduino-STM32-CAN/tree/master/stm32f103

do not use the `SPI` bus for connection.

@nopnop2002 Could you help me to select the necessary code based on your libraries for my harware🙂?

**Comment by nopnop2002** [comment]
This library may be usable with STM32F411.
However, I have never used this library with STM32F411.

https://github.com/coryjfowler/MCP_CAN_lib

There is no code for MCP2515 + SN65HVD230 in my repository.

**Comment by brightproject** [comment]
> However, I have never used this library with STM32F411

Yes, I have tried [this](https://github.com/coryjfowler/MCP_CAN_lib/blob/master/mcp_can.cpp) library, as well as [another](https://github.com/Longan-Labs/Arduino_CAN_BUS_MCP2515/blob/master/mcp_canbus.cpp) one that is more versatile.
Both libraries in codes work +/- the same.
I'm trying this simple code example
```
#include <Arduino.h>
#include <mcp_can.h>

// CAN
const int CAN_CS_PIN = PA4;

// int8_t Airspeed = 0;
// int32_t Airspeed = 0;
  unsigned int Airspeed = 0;
// unsigned long Airspeed = 0;
bool countup[1];

unsigned char canMsg[8] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};

const unsigned int CAN_ID = 183; // CAN Msg ID in DEC
const unsigned int Period = 100; // How often message sent in milliseconds
unsigned long Timestamp = 0; // when was the last message sent

MCP_CAN CAN(CAN_CS_PIN);  // Set CS pin

void setup()
{
 Serial.begin(115200);

    // while (CAN_OK != CAN.begin(MCP_ANY, CAN_500KBPS, MCP_8MHZ)) { // init can bus : baudrate = 500k
    while(CAN.begin(MCP_ANY, CAN_125KBPS, MCP_8MHZ) != CAN_OK) {
    // while(CAN_OK != CAN.begin(CAN_125KBPS, MCP_8MHZ)) {
      Serial.println("Unable to begin CAN BUS");
      delay(1000);
    }
    CAN.setMode(MCP_NORMAL);
    Serial.println("CAN BUS Shield init ok!");
  
} // SETUP

void loop()
{

if (millis() > Timestamp + Period) {

  if (Airspeed <= 100) {
    countup[0] = true;
  } 
  
  else if (Airspeed >= 1000) {
    countup[0] = false;
  }

  if (countup[0]) Airspeed += 5;
  else Airspeed -= 5;

  // canMsg[0] = Airspeed;
  // canMsg[1] = Airspeed >> 8;
  // canMsg[2] = Airspeed >> 16;
  // canMsg[3] = Airspeed >> 24;

  canMsg[0] = 1;
  canMsg[1] = 2;
  canMsg[2] = 3;
  canMsg[3] = 4;

 Serial.print(canMsg[0], HEX);
  Serial.print(".");
  Serial.print(canMsg[1], HEX);
  Serial.print(".");
  Serial.print(canMsg[2], HEX);
  Serial.print(".");
  Serial.println(canMsg[3], HEX);

  CAN.sendMsgBuf(CAN_ID, 0, 8, canMsg); 
  
  Timestamp = millis();
}

} // LOOP
```

The serial port data goes as expected.

> 4E.2.0.0
> 49.2.0.0
> 44.2.0.0
> 3F.2.0.0
> 3A.2.0.0
> 35.2.0.0
> 30.2.0.0
> 2B.2.0.0
> 26.2.0.0
> 21.2.0.0

Do you know what might be the reason?

There's complete nonsense with the can, the first frame sends 15 and that's it, then it freezes in all frames.

One
![can_frame_1](https://github.com/user-attachments/assets/0e356025-182d-41c2-a60c-0199f01da500)
Two
![can_frame_2](https://github.com/user-attachments/assets/fac28741-63d2-4208-861d-a777ab0dee2e)

I read somewhere that the `MCP2515` modules have an `8 MHz` quartz crystal and it doesn't work with some library normally, maybe I'm in exactly this situation.
I'll try to solder a `16 MHz` quartz crystal or use another module.

**Comment by nopnop2002** [comment]
Arduino_Core_STM32 supports SPI library, but only works in Transaction SPI Mode.
This may be related.

- Legacy SPI Mode   
SPI speed depends on the CPU frequency.   
STM32 does not work because it has various CPU frequencies.
```
SPI.begin()
SPI.setClockDivider(divider)
SPI.setDataMode(mode)
SPI.setBitOrder(order)
SPI.transfer(data);
```

- Transaction SPI Mode   
SPI speed NOT depends on the CPU frequency.   
Therefore, it works correctly with STM32.
```
SPI.begin()
SPI.beginTransaction(SPISettings(speed, order, mode))
SPI.transfer(data);
SPI.endTransaction()
```

**Comment by nopnop2002** [comment]
Transmission was possible with STM32F411 + mcp_can.
For the CAN wire, I used a ```twisted pair``` instead of a single wire.
Since STM32 does not have an INIT pin, I think reception will not work.
```
// CAN Send Example
//

#include <mcp_can.h>
#include <SPI.h>

//MCP_CAN CAN0(10);     // Set CS to pin 10
MCP_CAN CAN0(PA4);     // Set CS to pin 10

//#define SPEED CAN_125KBPS
//#define SPEED CAN_250KBPS
#define SPEED CAN_500KBPS
//#define SPEED CAN_1000KBPS

void setup()
{
  Serial.begin(115200);
  Serial.print("CAN speed=");
  Serial.println(SPEED);

  // Initialize MCP2515 running at 16MHz with a baudrate of 125kb/s and the masks and filters disabled.
  if(CAN0.begin(MCP_STDEXT, SPEED, MCP_8MHZ) == CAN_OK) {
  //if(CAN0.begin(MCP_ANY, SPEED, MCP_8MHZ) == CAN_OK) {
    Serial.println("MCP2515 Initialized Successfully!");
  } else {
    Serial.println("Error Initializing MCP2515...");
    while(1);
  }
  CAN0.setMode(MCP_NORMAL);   // Change to normal mode to allow messages to be transmitted
}


void loop()
{
  byte frame[8] = {0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17};
  static uint8_t sendLen = 0;
  // send data:  ID = 0x100, Standard CAN Frame, Data length = 8 bytes, 'data' = array of data bytes to send

  static unsigned long extID = 0x10000100;

  byte sndStat = CAN0.sendMsgBuf(extID, 1, sendLen, frame);
  if(sndStat == CAN_OK){
    Serial.println("Message Sent Successfully!");
  } else {
    Serial.println("Error Sending Message...");
  }

  extID++;
  if (extID > 0x1000010F) extID = 0x10000100;
  sendLen++;
  if (sendLen > 8) sendLen = 0;
  
  delay(1000);   // send data per 1000ms
}
```

```
CAN speed=13
Entering Configuration Mode Successful!
Setting Baudrate Successful!
MCP2515 Initialized Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
Message Sent Successfully!
```

**Comment by brightproject** [comment]
This is great news, thank you @nopnop2002 
Please tell me how you debug the `CAN` bus, what equipment do you use to check sending and receiving messages, in addition to outputting to the serial port?
Could you please check this code?

```
#include <Arduino.h>
#include <mcp_can.h>

// CAN
const int CAN_CS_PIN = PA4;

// int8_t Airspeed = 0;
// int32_t Airspeed = 0;
  unsigned int Airspeed = 0;
// unsigned long Airspeed = 0;
bool countup[1];

unsigned char canMsg[8] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};

const unsigned int CAN_ID = 183; // CAN Msg ID in DEC
const unsigned int Period = 100; // How often message sent in milliseconds
unsigned long Timestamp = 0; // when was the last message sent

MCP_CAN CAN(CAN_CS_PIN);  // Set CS pin

void setup()
{
 Serial.begin(115200);

    // while (CAN_OK != CAN.begin(MCP_ANY, CAN_500KBPS, MCP_8MHZ)) { // init can bus : baudrate = 500k
    while(CAN.begin(MCP_ANY, CAN_125KBPS, MCP_8MHZ) != CAN_OK) {
    // while(CAN_OK != CAN.begin(CAN_125KBPS, MCP_8MHZ)) {
      Serial.println("Unable to begin CAN BUS");
      delay(1000);
    }
    CAN.setMode(MCP_NORMAL);
    Serial.println("CAN BUS Shield init ok!");
  
} // SETUP

void loop()
{

if (millis() > Timestamp + Period) {

  if (Airspeed <= 100) {
    countup[0] = true;
  } 
  
  else if (Airspeed >= 1000) {
    countup[0] = false;
  }

  if (countup[0]) Airspeed += 5;
  else Airspeed -= 5;

  // canMsg[0] = Airspeed;
  // canMsg[1] = Airspeed >> 8;
  // canMsg[2] = Airspeed >> 16;
  // canMsg[3] = Airspeed >> 24;

  canMsg[0] = 1;
  canMsg[1] = 2;
  canMsg[2] = 3;
  canMsg[3] = 4;

 Serial.print(canMsg[0], HEX);
  Serial.print(".");
  Serial.print(canMsg[1], HEX);
  Serial.print(".");
  Serial.print(canMsg[2], HEX);
  Serial.print(".");
  Serial.println(canMsg[3], HEX);

  CAN.sendMsgBuf(CAN_ID, 0, 8, canMsg); 
  
  Timestamp = millis();
}

} // LOOP
```

I check sending to `CAN` bus using `logic analyzer`, and the values ​​in it do not increase, they are stopped at `15`.

![384661340-0e356025-182d-41c2-a60c-0199f01da500](https://github.com/user-attachments/assets/12ea5683-2909-4335-8371-0c20a04f0539)


![384661342-fac28741-63d2-4208-861d-a777ab0dee2e](https://github.com/user-attachments/assets/c51f41e4-3555-41d2-bf65-30d5570c947b)

And this is either a `signal analyzer` problem or a `CAN` transmitter problem.
I tried this solution

> https://github.com/latonita/arduino-canbus-monitor

But I could not get it to work.

**Comment by nopnop2002** [comment]
>Could you please check this code?

I don't know if there is a problem with your code.
The code I provided works correctly if there are no problems below.


- There is no receiving app on CanBus.
- The speed does not match the receiver.
- There is no terminating resistor on the CanBus.
- There are three terminating resistors on the CanBus.
- The resistance value of the terminating resistor is incorrect.
- 3.3V transceiver and 5V transceiver are mixed.   
 Use +1V Ground Shift using Split Termination.   
 Check out Figure 7 [here](http://www.ti.com/lit/an/slla337/slla337.pdf).   
- Stub length in CAN bus is too long.   
 ISO11898 Standard specifies a maximum bus length of 40m and maximum stub length of 0.3m at 1Mbps.
 See [here](https://e2e.ti.com/support/interface-group/interface/f/interface-forum/378932/iso1050-can-bus-stub-length).   
- Noise effects.   
 It occurs when the wire cable is thin or wire cable is crossing.   
 It is preferable to use wires that are noise-proof.

**Comment by brightproject** [comment]
> * Check out Figure 7 [here](http://www.ti.com/lit/an/slla337/slla337.pdf).

Thank you, I will study the material.
I am surprised that the `3.3. volt` transceiver has a slight imbalance of the two signals😞

![can_5_3v3](https://github.com/user-attachments/assets/53a0503f-7383-4b30-a7f1-32dde5e7a4ac)

It turns out that this event can also complicate the transmission of data over the `CAN` bus using the `SN65HVD230` transceiver?
Your code works for me, and my code works too.
I figured it out yesterday, and it turned out that my `Saleao` signal analyzer does not display the change of the date field on the `CAN` bus.

**Comment by nopnop2002** [comment]
>3.3V transceiver and 5V transceiver are mixed.

GPIOs (PA4, 5, 6, 7) used by STM32F411's SPI are 5 V tolerant I/O, so STM32F411 can use 5 V transceivers.

See here.
Table 8. STM32F411xC/xE pin definitions
If the I/O structure is FT, it is a 5 V tolerant I/O.
https://www.st.com/resource/en/datasheet/stm32f411ce.pdf
